# SPDX-FileCopyrightText: Timoth√©e Ravier <tim@siosm.fr>
# SPDX-License-Identifier: CC0-1.0

title: "extensions.fcos.fr (Community)"
description: "Community sourced sysexts for Fedora"
baseurl: "/community"
url: "https://fedora-sysexts.github.io"
permalink: "/:title/"
markdown: "kramdown"
kramdown:
  typographic_symbols:
    ndash: "--"
    mdash: "---"

remote_theme: just-the-docs/just-the-docs@v0.8.1
plugins:
  - jekyll-remote-theme

# Exclude from processing.
exclude:
   - justfile
   - Gemfile
   - Gemfile.lock
   - vendor

# Aux links for the upper right navigation
aux_links:
  "Sources on GitHub":
    - "https://github.com/fedora-sysexts/community"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
